apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terraform-runner-clusterrole
rules:
  # This rule covers certain core API resources across *all* namespaces.
  # Add or remove resources/verbs as needed for your use case.
- apiGroups: [""]
  resources:
    - namespaces
    - secrets
    - configmaps
    - services
    - pods
    - persistentvolumeclaims
    - serviceaccounts
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch

  # If you need to manage CRDs or other resources from "apps" API group, add another rule:
- apiGroups: ["apps"]
  resources:
    - deployments
    - statefulsets
    - daemonsets
    - replicasets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch

- apiGroups: ["networking.k8s.io"]
  resources:
    - networkpolicies
    - ingresses
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete

- apiGroups: ["policy"]
  resources:
    - poddisruptionbudgets
  verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
    - update

- apiGroups: ["batch"]
  resources:
    - jobs
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete

- apiGroups: ["autoscaling"]
  resources:
    - horizontalpodautoscalers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
   
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terraform-runner-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: terraform-runner-clusterrole  # must match the name of the ClusterRole above
subjects:
  - kind: ServiceAccount
    name: "terraform-runner"
    namespace: "default"
