apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-job
  namespace: default
  labels:
    app.kubernetes.io/instance: stackgen-app-deployment
spec:
  template:
    spec:
      serviceAccountName: terraform-runner
      restartPolicy: Never
      containers:
      - name: terraform-runner
        image: "gcr.io/platform-439702/terraform-deployer:1.0"
        env:
          - name: PROJECT_ID
            value: "[project_id]"   # placeholder matches the name in schema.yaml
          - name: REGION
            value: "[region]"
          - name: SUFFIX
            value: "[region]"
          - name: DOMAIN
            value: "[domain]"
          # For PAT, typically you'd use a Secret, but as an example:
          - name: STACKGEN_PAT
            value: "[STACKGEN_PAT]"
