apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: stackgen-app-deployment
spec:
  addOwnerRef: true
  descriptor:
    version: "1.0.0"
    description: "Deploys infrastructure and applications with Terraform"
    type: "stackgen"
  componentKinds:
    - group: ""            
      kind: "Job"
    - group: "rbac.authorization.k8s.io"
      kind: "Role"
    - group: "rbac.authorization.k8s.io"
      kind: "RoleBinding"
    - group: "rbac.authorization.k8s.io"   # Add these lines
      kind: "ClusterRole"
    - group: "rbac.authorization.k8s.io"
      kind: "ClusterRoleBinding"
  selector:
    matchLabels:
      app.kubernetes.io/instance: stackgen-app-deployment
