x-google-marketplace:
  schemaVersion: v2
  partnerId: "stackgen-gcp-marketplace"  # Replace with your actual Partner ID
  solutionId: "stackgen-enterprise-platform-k8s-v2.endpoints.stackgen-gcp-marketplace.cloud.goog" # Replace with your actual Product ID
  applicationApiVersion: v1beta1
  publishedVersion: "4.2.8"
  publishedVersionMetadata:
    releaseNote: "Initial release with Job support."
  images:
    deployer:
      properties:
        terraformRunnerImage:
          type: FULL

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  domain:
    type: string
    title: Domain
    description: Domain for deployment.
  suffix:
    type: string
    title: suffix
    description: suffix example name.
    default: marketplace
  stackgenPat:
    type: string
    title: Stackgen Personal Access Token
    description: Access token for Stackgen.
  pre_shared_cert_name:
    type: string
    title: Pre-shared Certificate Name
    description: The name of the pre-shared SSL certificate created in your GCP account. This certificate is used for HTTPS connections in the GCE Ingress configuration.
  global_static_ip_name:
    type: string
    title: Global Static IP Name
    description: The name of the global static IP reserved in your GCP account. This IP is used for associating with GCE Ingress.
  guildEnabled:
    type: boolean
    title: Enable Guild routing
    description: Enable NGINX routes to a StackGen Guild release installed in this namespace.
    default: false
  appcdVersion:
    type: string
    title: AppCD image version
    default: v2025.1.3
  iacgenVersion:
    type: string
    title: IAC Gen image version
    default: v0.22.0
  uiVersion:
    type: string
    title: AppCD UI image version
    default: v0.10.11
  exporterVersion:
    type: string
    title: Exporter image version
    default: v0.4.0
  llmGatewayVersion:
    type: string
    title: LLM Gateway image version
    default: v0.2.3
  vaultVersion:
    type: string
    title: Vault image version
    default: v0.1.0
  guildVersion:
    type: string
    title: Guild image version
    default: v0.2.28-hotfix.4
  gatewayVersion:
    type: string
    title: Guild Gateway image version
    default: v0.2.28-hotfix.2
  guildUiVersion:
    type: string
    title: Guild UI image version
    default: v0.2.28-hotfix.2
  operatorServiceAccount:
      type: string
      title: Operator Service Account
      x-google-marketplace:
        type: SERVICE_ACCOUNT
        serviceAccount:
          description: >
            Service account used by Operator deployment to manage cluster resources.
          roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
            - apiGroups: [""]
              resources:
                - namespaces
                - secrets
                - configmaps
                - services
                - pods
                - persistentvolumeclaims
                - serviceaccounts
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups: ["apps"]
              resources:
                - deployments
                - statefulsets
                - daemonsets
                - replicasets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups: ["batch"]
              resources:
                - jobs
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups: ["networking.k8s.io"]
              resources:
                - networkpolicies
                - ingresses
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups: ["policy"]
              resources:
                - poddisruptionbudgets
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups: ["autoscaling"]
              resources:
                - horizontalpodautoscalers
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
required:
  - name
  - namespace
  - domain
  - stackgenPat
