x-google-marketplace:
  schemaVersion: v2
  partnerId: "my-partner-id"  # Replace with your actual Partner ID
  solutionId: "my-product-id" # Replace with your actual Product ID
  applicationApiVersion: v1beta1
  publishedVersion: '0.1.0'
  publishedVersionMetadata:
    releaseNote: "Initial release with Job support."
  images:
    terraformRunner:
      properties:
        terraformRunnerImage:
          type: FULL

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  projectId:
    type: string
    title: GCP Project ID
    description: Google Cloud project ID.
  region:
    type: string
    title: GCP Region
    description: Deployment region.
  domain:
    type: string
    title: Domain
    description: Domain for deployment.
  stackgenPat:
    type: string
    title: Stackgen Personal Access Token
    description: Access token for Stackgen.

  # Example of a potential additional property (if needed):
  replicas:
    type: integer
    title: Job Replica Count
    description: Number of job replicas to deploy.

required:
  - name
  - namespace
  - projectId
  - region
  - domain
  - stackgenPat
