x-google-marketplace:
  schemaVersion: v2
  partnerId: "my-partner-id"  # Replace with your actual Partner ID
  solutionId: "my-product-id" # Replace with your actual Product ID
  applicationApiVersion: v1beta1
  publishedVersion: '1.0.0'
  publishedVersionMetadata:
    releaseNote: "Initial release with Job support."
  images:
    deployer:
      properties:
        terraformRunnerImage:
          type: FULL

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  projectId:
    type: string
    title: GCP Project ID
    description: Google Cloud project ID.
    default: "platform-439702"
  region:
    type: string
    title: GCP Region
    description: Deployment region.
    default: "us-central1"
  domain:
    type: string
    title: Domain
    description: Domain for deployment.
    default: "app.test"
  suffix:
    type: string
    title: suffix
    description: suffix example name.
    default: "deployer"
  stackgenPat:
    type: string
    title: Stackgen Personal Access Token
    description: Access token for Stackgen.
    default: "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"
  operatorServiceAccount:
      type: string
      title: Operator Service Account
      x-google-marketplace:
        type: SERVICE_ACCOUNT
        serviceAccount:
          description: >
            Service account used by Operator deployment to manage cluster resources.
          roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
            - apiGroups: [""]
              resources:
                - namespaces
                - secrets
                - configmaps
                - services
                - pods
                - persistentvolumeclaims
                - serviceaccounts
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups: ["apps"]
              resources:
                - deployments
                - statefulsets
                - daemonsets
                - replicasets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups: ["batch"]
              resources:
                - jobs
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups: ["networking.k8s.io"]
              resources:
                - networkpolicies
                - ingresses
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups: ["policy"]
              resources:
                - poddisruptionbudgets
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups: ["autoscaling"]
              resources:
                - horizontalpodautoscalers
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
required:
  - name
  - namespace
  - projectId
  - region
  - domain
  - stackgenPat