properties:
  imageTester:
    type: string
    default: marketplace.gcr.io/google/debian10:latest
  domain:
    type: string
    title: Domain
    description: Domain for deployment.
    default: "go.cloud.stackgen.com"
  stackgenPat:
    type: string
    title: Stackgen Personal Access Token
    description: Access token for Stackgen.
    default: "YOUR_STACKGEN_PAT"
  pre_shared_cert_name:
    type: string
    title: Pre-shared Certificate Name
    description: The name of the pre-shared SSL certificate created in your GCP account. This certificate is used for HTTPS connections in the GCE Ingress configuration.
    default: "go-cloud-stackgen-com"
  global_static_ip_name:
    type: string
    title: Global Static IP Name
    description: The name of the global static IP reserved in your GCP account. This IP is used for associating with GCE Ingress.
    default: 34.8.2.217
